create table bank (
    id bigint not null,
    primary key (id)
);

create table stock (
    id bigint generated by default as identity,
    name varchar(255) not null,
    primary key (id),
    constraint uk_stock_name unique (name)
);

create table wallet (
    id varchar(255) not null,
    primary key (id)
);

create table bank_stock (
    id bigint generated by default as identity,
    bank_id bigint not null,
    stock_id bigint not null,
    quantity integer not null,
    primary key (id),
    constraint uk_bank_stock_bank_stock unique (bank_id, stock_id),
    constraint fk_bank_stock_bank foreign key (bank_id) references bank (id),
    constraint fk_bank_stock_stock foreign key (stock_id) references stock (id),
    constraint ck_bank_stock_quantity check (quantity >= 0)
);

create table wallet_position (
    id bigint generated by default as identity,
    wallet_id varchar(255) not null,
    stock_id bigint not null,
    quantity integer not null,
    primary key (id),
    constraint uk_wallet_position_wallet_stock unique (wallet_id, stock_id),
    constraint fk_wallet_position_wallet foreign key (wallet_id) references wallet (id),
    constraint fk_wallet_position_stock foreign key (stock_id) references stock (id),
    constraint ck_wallet_position_quantity check (quantity > 0)
);

create table audit_log (
    id bigint generated by default as identity,
    type varchar(255) not null,
    wallet_id varchar(255) not null,
    stock_name varchar(255) not null,
    primary key (id)
);
